"""SeaTrace AI M3 GIS & Database Module.

Owned by M3: Nithish (GIS / Database)
Master Contract: v4.1
"""

from sea_trace.database.config import settings, DatabaseSettings
from sea_trace.database.connection import engine, SessionLocal, get_db_session, get_async_db
from sea_trace.database.models import (
    Base,
    Incident,
    Scene,
    Spill,
    DriftRun,
    AISFix,
    Track,
    Candidate,
    Evidence,
    StageLog,
    Provenance,
    AOI,
)
from sea_trace.database.schemas import (
    IncidentState,
    StageName,
    StageStatus,
    ErrorResponse,
    AOICreate,
    AOIResponse,
    IncidentCreate,
    IncidentResponse,
    SceneCreate,
    SceneResponse,
    SpillCreate,
    SpillResponse,
    DriftRunCreate,
    DriftRunResponse,
    AISFixCreate,
    AISFixResponse,
    TrackCreate,
    TrackResponse,
    CandidateCreate,
    CandidateResponse,
    EvidenceCreate,
    EvidenceResponse,
    StageLogCreate,
    StageLogResponse,
    ProvenanceCreate,
    ProvenanceResponse,
)
from sea_trace.database.queries import (
    build_spacetime_ais_filter_sql,
    query_candidate_vessels_in_spacetime,
    query_tracks_in_spacetime,
    format_partition_name,
    get_partition_dates_for_range,
    get_partition_names_for_range,
    ensure_partitions_for_range,
)
from sea_trace.database.aoi import (
    OutOfAOIError,
    check_footprint_intersects_aoi,
    validate_and_register_scene,
)
from sea_trace.database.storage import FileStoreManager, filestore
from sea_trace.database.repository import SeaTraceRepository

__all__ = [
    "settings",
    "DatabaseSettings",
    "engine",
    "SessionLocal",
    "get_db_session",
    "get_async_db",
    "Base",
    "Incident",
    "Scene",
    "Spill",
    "DriftRun",
    "AISFix",
    "Track",
    "Candidate",
    "Evidence",
    "StageLog",
    "Provenance",
    "AOI",
    "IncidentState",
    "StageName",
    "StageStatus",
    "ErrorResponse",
    "AOICreate",
    "AOIResponse",
    "IncidentCreate",
    "IncidentResponse",
    "SceneCreate",
    "SceneResponse",
    "SpillCreate",
    "SpillResponse",
    "DriftRunCreate",
    "DriftRunResponse",
    "AISFixCreate",
    "AISFixResponse",
    "TrackCreate",
    "TrackResponse",
    "CandidateCreate",
    "CandidateResponse",
    "EvidenceCreate",
    "EvidenceResponse",
    "StageLogCreate",
    "StageLogResponse",
    "ProvenanceCreate",
    "ProvenanceResponse",
    "build_spacetime_ais_filter_sql",
    "query_candidate_vessels_in_spacetime",
    "query_tracks_in_spacetime",
    "format_partition_name",
    "get_partition_dates_for_range",
    "get_partition_names_for_range",
    "ensure_partitions_for_range",
    "OutOfAOIError",
    "check_footprint_intersects_aoi",
    "validate_and_register_scene",
    "FileStoreManager",
    "filestore",
    "SeaTraceRepository",
]
